s-- ==========================================
-- URGENT FIX: RESET SIGNUP TRIGGER
-- ==========================================
-- This script completely removes old triggers and replaces them 
-- RUN THIS SCRIPT IN SUPABASE SQL EDITOR

-- 1. Make student_id an Auto-Incrementing Identity Column (Starting at 1800)
-- We use "GENERATED BY DEFAULT" so manual inserts (if ever needed) can still work.
ALTER TABLE student 
ALTER COLUMN student_id 
ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 1800 INCREMENT BY 1);

-- 2. If the column was already an identity column, restart it (Safety check):


-- 3. Ensure the Function is correct (Optional, but good for cleanup)
CREATE OR REPLACE FUNCTION trg_create_login()
RETURNS TRIGGER AS $$
BEGIN
    -- We only try to insert if it doesn't exist.
    -- The JS handles the main insertion now, this is just a backup.
    IF NOT EXISTS (
        SELECT 1 FROM user_auth WHERE student_id = NEW.student_id
    ) THEN
        INSERT INTO user_auth(student_id, username, password_hash, role)
        VALUES (
            NEW.student_id,
            lower(replace(NEW.name,' ','')) || NEW.student_id,
            'default_hash',
            'Student'
        )
        ON CONFLICT (username) DO NOTHING;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
